name: Build

on:
  push:
    branches: [ master, updates ]

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: ilammy/setup-nasm@v1.2.1
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Update binaries
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          nmake
          xcopy /Y dist\*.node binaries
          ls

      - name: Upload prebuild-assets
        uses: actions/upload-artifact@v2
        with:
          name: windows-binaries
          path: binaries
          retention-days: 1

  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Update binaries
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.2.app || true
          sudo apt update || true
          sudo apt install -y g++-aarch64-linux-gnu || true
          make
          mkdir binaries
          cp dist/*.node binaries
          ls
      - name: Upload prebuild-assets
        uses: actions/upload-artifact@v2
        with:
          name: unix-binaries
          path: binaries
          retention-days: 1

  aggregate_binaries:
    needs: [build-windows, build-unix]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: download windows binaries
        uses: actions/download-artifact@v2
        with:
          name: windows-binaries
          path: binaries

      - name: download unix binaries
        uses: actions/download-artifact@v2
        with:
          name: unix-binaries
          path: binaries

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: binaries

      - name: configure Git
        run: |
          git config --global user.email "robot@trufflesuite.com"
          git config --global user.name "Robot"

      - run: git add binaries
      - run: git commit -a -m "[GitHub Actions] Update binaries"
      - run: git git push "https://robot:${{ secrets.SECRET }}@github.com/$GITHUB_REPOSITORY" "${GITHUB_REF##*/}"